version: 0.2

 
phases:
  pre_build:
    commands:
    - docker login -u $username -p $password
    - echo "Building Docker image..."
    - docker build -t pro1 .


  post_build:
    commands:
      - echo "Tagging image for Docker Hub..."
      - docker tag pro1 haritdockerhub/brain-tasks-app:latest
      - echo "Pushing image to Docker Hub..."
      - docker push haritdockerhub/brain-tasks-app:latest

artifacts:
  files:
    - '**/*'
  
