version: 0.2

env:
  variables:
    DOCKER_REGISTRY_USERNAME: "username"
    DOCKER_REGISTRY_PASSWORD: "password"
    DOCKER_REGISTRY_URL: "https://index.docker.io/v1/"

 phases:
  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo $DOCKER_REGISTRY_PASSWORD | docker login $DOCKER_REGISTRY_URL -u $DOCKER_REGISTRY_USERNAME --password-stdin
      - echo "Building Docker image..."
      - docker build -t pro1 .

  post_build:
    commands:
      - echo "Tagging image for Docker Hub..."
      - docker tag pro1 harit-hubgit/brain-tasks-app:latest
      - echo "Pushing image to Docker Hub..."
      - docker push harit-hubgit/brain-tasks-app:latest

artifacts:
  files:
    - '**/*'
  base-directory: Brain-Tasks-app
